# Generated by Django 3.1.6 on 2021-02-27 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210227_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbyweight',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category'),
        ),
    ]
